### ISSUE TITLE
Crash in xp accessing jzIntv Intellivoice, ECS, JLP settings in Ribbon

### ISSUE THREAD

**Issue by intvsteve** [intvsteve/VINTage#24]
System.InvalidOperationException: This Visual is not connected to a PresentationSource.
   at System.Windows.Media.Visual.PointToScreen(Point point)
   at Microsoft.Windows.Controls.Ribbon.RibbonMenuButton.UpdateDropDownPosition(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by intvsteve** [comment]
Bug was due to the different behavior of RibbonComboBox in the older Ribbon controls library needed for WIndows xp support. This was NOT an issue in Vista and later.
