### ISSUE TITLE
Unhandled exception running in debugger and waking system from sleep

### ISSUE THREAD

**Issue by intvsteve** [intvsteve/VINTage#335]
### Operating system version
Windows 10

### Program version (from About box)
N/A

### Expected behavior
Don't crash

### Actual behavior
Crash

### Steps to reproduce
Unsure. The system had been in use for about a week, with various remote desktop attach / detach, even a router replacement.

### Crash log if available (paste or attach)
System.Runtime.InteropServices.COMException (0x80263001): {Desktop composition is disabled} The operation could not be completed because desktop composition is disabled. (Exception from HRESULT: 0x80263001)
   at Standard.NativeMethods.DwmExtendFrameIntoClientArea(IntPtr hwnd, MARGINS& pMarInset)
   at System.Windows.Shell.WindowChromeWorker._ExtendGlassFrame()
   at System.Windows.Shell.WindowChromeWorker._UpdateFrameState(Boolean force)
   at System.Windows.Shell.WindowChromeWorker._ApplyNewCustomChrome()
   at System.Windows.Shell.WindowChromeWorker.SetWindowChrome(WindowChrome newChrome)
   at System.Windows.Shell.WindowChrome._OnChromeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.StyleHelper.InvalidateResourceDependents(DependencyObject container, ResourcesChangeInfo info, FrugalStructList`1& resourceDependents, Boolean invalidateVisualTreeToo)
   at System.Windows.TreeWalkHelper.InvalidateStyleAndReferences(DependencyObject d, ResourcesChangeInfo info, Boolean containsTypeOfKey)
   at System.Windows.TreeWalkHelper.OnResourcesChanged(DependencyObject d, ResourcesChangeInfo info, Boolean raiseResourceChangedEvent)
   at System.Windows.TreeWalkHelper.OnResourcesChangedCallback(DependencyObject d, ResourcesChangeInfo info, Boolean visitedViaVisualTree)
   at System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   at System.Windows.TreeWalkHelper.InvalidateOnResourcesChange(FrameworkElement fe, FrameworkContentElement fce, ResourcesChangeInfo info)
   at System.Windows.SystemResources.InvalidateTreeResources(Object args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[ErrorLog_2019-12-06-18-07-15-554.txt](https://github.com/intvsteve/VINTage/files/3934480/ErrorLog_2019-12-06-18-07-15-554.txt)

**Comment by intvsteve** [comment]
Crash is in desktop window manager native call, called from the Windows API Code Pack's Shell code.

**Comment by intvsteve** [comment]
More details... Had previously been using a remote desktop connection from old version of remote desktop on Mac running Mac OS 10.8.5. Unclear if that mac was attempting to reconnect at the time of the local attempt to use machine. It may be a contributing factor.
